import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service and Disclosures | Adviso",
  description: "Adviso Terms of Service and AI academic disclosures.",
};

const termsSections = [
  {
    title: "1. Agreement to These Terms",
    paragraphs: [
      "These Terms of Service (\"Terms\") govern your access to and use of Adviso, including our website, software, AI academic planning tools, recommendations, content, and related services (collectively, the \"Service\"). By using the Service, you agree to these Terms. If you do not agree, do not use the Service.",
    ],
  },
  {
    title: "2. What Adviso Does",
    paragraphs: [
      "Adviso is an AI-powered academic planning assistant that helps users explore courses, schedules, academic pathways, and planning options. Adviso may generate suggestions based on information you provide, public information, third-party data, and automated analysis.",
      "Adviso is not a university, academic advisor, registrar, degree auditor, counselor, or enrollment authority. Adviso does not enroll you in courses, guarantee graduation, satisfy degree requirements, replace official advising, or provide official determinations about your academic status.",
    ],
  },
  {
    title: "3. Independent Service; No University Affiliation",
    paragraphs: [
      "Adviso is an independent service. Unless we expressly state otherwise in a signed agreement, Adviso is not affiliated with, sponsored by, endorsed by, approved by, or operated by the University of California, Davis; the University of California; The Regents of the University of California; or any other educational institution.",
      "Any references to \"UC Davis,\" \"University of California, Davis,\" course names, majors, requirements, or related academic information are for identification, compatibility, and informational purposes only.",
    ],
  },
  {
    title: "4. Important Academic Disclaimer",
    paragraphs: [
      "Academic requirements, course availability, prerequisites, catalog rules, major requirements, transfer rules, unit limits, graduation requirements, and enrollment policies can change. Adviso may be incomplete, outdated, or incorrect.",
      "You are responsible for verifying all academic decisions with official university sources, including your university catalog, department, registrar, degree audit tools, and official academic advisors. You should not rely solely on Adviso for enrollment, graduation, transfer, financial aid, immigration, scholarship, athletic eligibility, housing, employment, or other important decisions.",
    ],
  },
  {
    title: "5. Scheduling and Course Planning Responsibility",
    paragraphs: [
      "Adviso may generate schedules, course plans, prerequisite suggestions, graduation timelines, major-change plans, transfer plans, workload estimates, and related recommendations. These outputs are informational only and may be wrong, incomplete, outdated, infeasible, or incompatible with official requirements.",
      "You are solely responsible for checking whether any schedule or plan generated by Adviso is accurate, available, permitted, and appropriate for your situation before relying on it. This includes verifying course availability, time conflicts, prerequisites, restrictions, major requirements, unit limits, registration pass times, waitlist rules, graduation requirements, transfer requirements, financial aid requirements, visa or immigration requirements, athletic eligibility rules, and all applicable university policies.",
      "Adviso is not responsible for consequences resulting from your reliance on AI-generated schedules or plans, including missed requirements, delayed graduation, course enrollment issues, dropped courses, academic standing issues, financial aid consequences, transfer consequences, immigration consequences, or other academic, financial, personal, or professional outcomes.",
    ],
  },
  {
    title: "6. Eligibility",
    paragraphs: [
      "You must be at least 13 years old to use the Service. If you are under the age of majority where you live, you may use the Service only with permission from a parent or legal guardian. The Service is intended for college students, prospective college students, and related users, not children under 13.",
    ],
  },
  {
    title: "7. Accounts and User Information",
    paragraphs: [
      "You may need to create an account or provide information to use certain features. You agree to provide accurate information and keep your account secure. You are responsible for activity under your account.",
      "Do not provide another person's information without permission. Do not submit confidential, sensitive, or legally protected information unless you have the right to do so and understand how it will be used.",
    ],
  },
  {
    title: "8. Student Records and Sensitive Academic Information",
    paragraphs: [
      "You should not upload or enter official transcripts, degree audits, student ID numbers, non-public education records, financial aid records, disability accommodations, disciplinary records, medical records, immigration records, or other sensitive information unless Adviso specifically requests it and you choose to provide it.",
      "If you provide academic information, you represent that you have the right to provide it and that your use of Adviso does not violate any school policy, privacy law, confidentiality obligation, or third-party right.",
    ],
  },
  {
    title: "9. AI-Generated Output",
    paragraphs: [
      "The Service may use artificial intelligence. AI-generated content can be inaccurate, incomplete, outdated, biased, or unsuitable for your situation. AI output should be treated as a starting point for review, not a final answer.",
      "You are responsible for independently checking AI-generated suggestions before acting on them.",
    ],
  },
  {
    title: "10. Acceptable Use",
    paragraphs: ["You agree not to:"],
    bullets: [
      "Use the Service for unlawful, harmful, deceptive, abusive, or fraudulent purposes.",
      "Attempt to access another user's account or data.",
      "Submit information you do not have the right to use.",
      "Scrape, reverse engineer, attack, overload, or interfere with the Service.",
      "Use the Service to make official decisions about another student without authorization.",
      "Misrepresent Adviso as an official university service.",
      "Use Adviso output in a way that violates academic integrity rules, school policies, or applicable law.",
    ],
  },
  {
    title: "11. User Content",
    paragraphs: [
      "You may submit information, prompts, academic data, preferences, files, feedback, and other content (\"User Content\"). You keep ownership of your User Content.",
      "You grant Adviso a limited license to use, host, process, display, transmit, and analyze User Content as needed to provide, secure, improve, and support the Service. We will handle User Content as described in our Privacy Policy.",
    ],
  },
  {
    title: "12. Feedback",
    paragraphs: [
      "If you provide suggestions, ideas, bug reports, or feedback, you allow us to use them without restriction or compensation to you.",
    ],
  },
  {
    title: "13. Service Changes and Beta Features",
    paragraphs: [
      "Adviso may change, suspend, discontinue, or limit any part of the Service at any time. Some features may be experimental or beta features. Beta features may be unstable, inaccurate, or removed.",
    ],
  },
  {
    title: "14. Third-Party Services and Data",
    paragraphs: [
      "Adviso may rely on third-party services, hosting providers, analytics tools, AI providers, authentication providers, payment processors, or public data sources. We are not responsible for third-party services, websites, data, or content.",
    ],
  },
  {
    title: "15. Intellectual Property",
    paragraphs: [
      "The Service, including its software, design, branding, workflows, text, graphics, and other materials, is owned by Adviso or its licensors and is protected by intellectual property laws. You may not copy, modify, distribute, sell, or create derivative works from the Service except as allowed by these Terms.",
      "All university names, course names, trademarks, and logos belong to their respective owners. Adviso does not claim ownership of third-party marks.",
    ],
  },
  {
    title: "16. Fees and Payments",
    paragraphs: [
      "Some features may be free, paid, or offered through a pilot. If paid features are offered, pricing and payment terms will be disclosed before purchase. Fees are non-refundable except as required by law or expressly stated at purchase.",
    ],
  },
  {
    title: "17. Termination",
    paragraphs: [
      "You may stop using Adviso at any time. We may suspend or terminate access if we believe you violated these Terms, created risk, caused harm, or used the Service improperly.",
    ],
  },
  {
    title: "18. Disclaimers",
    paragraphs: [
      "The Service is provided \"as is\" and \"as available.\" To the fullest extent permitted by law, Adviso disclaims all warranties, express or implied, including warranties of accuracy, reliability, availability, merchantability, fitness for a particular purpose, non-infringement, and error-free operation.",
      "Adviso does not guarantee academic outcomes, course availability, enrollment, transfer admission, major eligibility, graduation, degree completion, financial aid outcomes, grades, course difficulty, instructor quality, or any other result.",
    ],
  },
  {
    title: "19. Limitation of Liability",
    paragraphs: [
      "To the fullest extent permitted by law, Adviso and its owners, employees, contractors, affiliates, and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for lost profits, lost data, academic consequences, enrollment consequences, or reliance-based losses.",
      "To the fullest extent permitted by law, Adviso's total liability for all claims related to the Service will not exceed the greater of: (a) the amount you paid Adviso in the 3 months before the claim, or (b) $100.",
    ],
  },
  {
    title: "20. Indemnity",
    paragraphs: [
      "You agree to indemnify and hold harmless Adviso and its owners, employees, contractors, affiliates, and service providers from claims, losses, liabilities, damages, costs, and expenses arising from your use of the Service, your User Content, your violation of these Terms, or your violation of law or third-party rights.",
    ],
  },
  {
    title: "21. Governing Law",
    paragraphs: [
      "These Terms are governed by the laws of the State of California, without regard to conflict-of-law rules. Any dispute that is not resolved informally will be brought in the state or federal courts located in California, unless applicable law requires a different forum.",
    ],
  },
  {
    title: "22. Changes to These Terms",
    paragraphs: [
      "We may update these Terms from time to time. The updated version will be posted with a new effective date. Your continued use of the Service after changes become effective means you accept the updated Terms.",
    ],
  },
  {
    title: "23. Contact",
    paragraphs: ["Questions about these Terms may be sent to: Adviso, pengstromjr@gmail.com."],
  },
];

const disclosureSections = [
  {
    title: "1. AI Disclosure",
    paragraphs: [
      "Adviso uses artificial intelligence to generate academic planning suggestions, schedule ideas, course recommendations, summaries, explanations, and related outputs. AI-generated content may be inaccurate, incomplete, outdated, biased, or not suitable for your specific situation.",
      "You should verify all AI-generated information with official university sources before making academic, enrollment, financial, transfer, graduation, or other important decisions.",
    ],
  },
  {
    title: "2. Academic Planning Disclaimer",
    paragraphs: [
      "Adviso is an informational planning tool only. Adviso does not provide official academic advising, degree audits, enrollment decisions, graduation clearance, transfer admission decisions, financial aid advice, legal advice, immigration advice, medical advice, mental health advice, or professional counseling.",
      "Course availability, prerequisites, requirements, policies, unit limits, deadlines, and graduation rules may change. Adviso may not reflect the most current or complete information.",
    ],
  },
  {
    title: "3. UC Davis / University Non-Affiliation Disclosure",
    paragraphs: [
      "Adviso is an independent service. Adviso is not affiliated with, sponsored by, endorsed by, approved by, or operated by UC Davis, the University of California, The Regents of the University of California, or any academic department, unless expressly stated in a written agreement.",
      "References to UC Davis or other universities are for identification and informational purposes only. All university names, marks, and related materials belong to their respective owners.",
    ],
  },
  {
    title: "4. Unofficial Degree Checklist Disclosure",
    paragraphs: [
      "Any degree progress, requirement tracking, major checklist, or academic pathway shown by Adviso is unofficial. Adviso is not a UC Davis degree audit, registrar record, academic record, graduation evaluation, or official advising determination.",
      "You are responsible for confirming all requirements with official university catalogs, registrar tools, department websites, degree audit tools, and academic advisors.",
    ],
  },
  {
    title: "5. AI Schedule Disclaimer",
    paragraphs: [
      "Any schedule, course plan, graduation plan, or recommendation produced by Adviso is only a draft for your review. AI-generated schedules may be inaccurate, incomplete, outdated, unavailable, impossible to register for, or incompatible with official requirements.",
      "You are responsible for confirming every detail with official sources before acting on it. This includes course availability, meeting times, prerequisites, restrictions, unit limits, major requirements, GE requirements, registration pass times, waitlist rules, deadlines, graduation requirements, transfer requirements, financial aid requirements, and university policies.",
      "Adviso is not responsible if an AI-generated schedule is wrong, unavailable, conflicts with official requirements, delays graduation, causes enrollment issues, affects financial aid, affects transfer plans, or otherwise leads to a negative outcome.",
    ],
  },
  {
    title: "6. Course Discovery, Grades, and Instructor Data Disclosure",
    paragraphs: [
      "Adviso may display course recommendations, instructor information, ratings, historical grade data, workload estimates, or similar information. This information is informational only and may be incomplete, outdated, biased, limited, or inaccurate.",
      "Past grade distributions do not guarantee future grades. Instructor ratings do not guarantee instructor quality or course experience. Course recommendations do not guarantee enrollment availability, academic success, workload, grade outcome, or satisfaction.",
    ],
  },
  {
    title: "7. Data Source Disclosure",
    paragraphs: [
      "Adviso may rely on public information, user-provided information, third-party services, AI-generated analysis, and other sources. These sources may be incomplete, outdated, or incorrect.",
      "Official university catalogs, registrar records, department websites, degree audit tools, and academic advisors should be treated as authoritative.",
    ],
  },
  {
    title: "8. Student Data Disclosure",
    paragraphs: [
      "Do not enter sensitive information unless you understand how it may be used. This includes transcripts, student ID numbers, non-public education records, disability accommodations, medical information, financial aid records, immigration information, disciplinary information, or another student's information.",
      "Adviso does not need your UC Davis password or login credentials for official university systems.",
    ],
  },
  {
    title: "9. No Guarantee",
    paragraphs: [
      "Adviso does not guarantee course enrollment, schedule feasibility, prerequisite satisfaction, major admission, transfer admission, degree completion, graduation, grades, academic performance, financial aid outcomes, instructor quality, course difficulty, or any other academic outcome.",
    ],
  },
];

function LegalSection({
  title,
  paragraphs,
  bullets,
}: {
  title: string;
  paragraphs: string[];
  bullets?: string[];
}) {
  return (
    <section className="space-y-3">
      <h2 className="text-xl font-bold text-gray-950 dark:text-white">{title}</h2>
      {paragraphs.map((paragraph) => (
        <p key={paragraph} className="text-sm leading-7 text-gray-700 dark:text-slate-300">
          {paragraph}
        </p>
      ))}
      {bullets && (
        <ul className="list-disc space-y-2 pl-5 text-sm leading-7 text-gray-700 dark:text-slate-300">
          {bullets.map((bullet) => (
            <li key={bullet}>{bullet}</li>
          ))}
        </ul>
      )}
    </section>
  );
}

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-gray-50 text-gray-950 dark:bg-slate-950 dark:text-white">
      <div className="mx-auto max-w-4xl px-5 py-8 sm:px-8 sm:py-12">
        <Link
          href="/"
          className="text-sm font-semibold text-[#002855] underline-offset-4 hover:underline dark:text-blue-300"
        >
          Back to Adviso
        </Link>

        <header className="mt-8 border-b border-gray-200 pb-8 dark:border-slate-800">
          <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#DAAA00]">
            Legal
          </p>
          <h1 className="mt-3 text-3xl font-black tracking-tight text-gray-950 dark:text-white sm:text-5xl">
            Adviso Terms of Service and Disclosures
          </h1>
          <div className="mt-5 space-y-1 text-sm text-gray-600 dark:text-slate-300">
            <p>
              <strong>Effective Date:</strong> 5/5/2026
            </p>
            <p>
              <strong>Service/Operator:</strong> Adviso
            </p>
            <p>
              <strong>Contact:</strong> pengstromjr@gmail.com
            </p>
          </div>
        </header>

        <article className="mt-10 space-y-10">
          <section>
            <h2 className="text-2xl font-black text-[#002855] dark:text-blue-300">
              Terms of Service
            </h2>
          </section>
          {termsSections.map((section) => (
            <LegalSection key={section.title} {...section} />
          ))}

          <section className="border-t border-gray-200 pt-10 dark:border-slate-800">
            <h2 className="text-2xl font-black text-[#002855] dark:text-blue-300">
              AI & Academic Disclosures
            </h2>
            <div className="mt-4 space-y-1 text-sm text-gray-600 dark:text-slate-300">
              <p>
                <strong>Effective Date:</strong> 5/5/2026
              </p>
              <p>
                <strong>Service/Operator:</strong> Adviso
              </p>
              <p>
                <strong>Contact:</strong> pengstromjr@gmail.com
              </p>
            </div>
          </section>
          {disclosureSections.map((section) => (
            <LegalSection key={section.title} {...section} />
          ))}
        </article>
      </div>
    </main>
  );
}
